#ifndef OUROBOROS_ERRNO_H
#define OUROBOROS_ERRNO_H

#define OU_ERR_SUCCESS			(0)
#define OU_ERR_UNKNOWN			(1)
#define OU_ERR_NO_MEMORY		(2)
#define OU_ERR_PERMISSION		(3)
#define OU_ERR_INVALID_ARGUMENT		(4)
#define OU_ERR_TLB_MISS			(5)
#define OU_ERR_NONCONTIGUOUS_MEMORY	(6)

#endif /* OUROBOROS_ERRNO_H */
