#ifndef OUROBOROS_ARCH_MIPS_ENTRY_H
#define OUROBOROS_ARCH_MIPS_ENTRY_H

#define ENTRY_POLICY_K0_K1	(0)
#define ENTRY_POLICY_K0_ROTR	(1)
#define ENTRY_POLICY_K1_ROTR	(2)
#define ENTRY_POLICY_K0_UL	(3)
#define ENTRY_POLICY_K1_UL	(4)
#define ENTRY_POLICY_UL_ROTR	(5)
#define ENTRY_POLICY_SHADOW	(6)

#endif /* OUROBOROS_ARCH_MIPS_ENTRY_H */
