#include <ouroboros/arch/mips/ikernel/shadow.h>
#include <ouroboros/arch/mips/asm.h>

void k_read_current_pss(struct ou_context *context)
{
#define RDPGPR_CONTEXT(n)				\
do {							\
	if (context->mask_regs & CTX_MASK_REG_GPR(n)) {	\
		RDPGPR(context->gpr.by_index[n], $##n);	\
	}						\
} while (0)

	__asm__(".set noat");
	RDPGPR_CONTEXT(1);
	__asm__(".set at");
	RDPGPR_CONTEXT(2);
	RDPGPR_CONTEXT(3);
	RDPGPR_CONTEXT(4);
	RDPGPR_CONTEXT(5);
	RDPGPR_CONTEXT(6);
	RDPGPR_CONTEXT(7);
	RDPGPR_CONTEXT(8);
	RDPGPR_CONTEXT(9);
	RDPGPR_CONTEXT(10);
	RDPGPR_CONTEXT(11);
	RDPGPR_CONTEXT(12);
	RDPGPR_CONTEXT(13);
	RDPGPR_CONTEXT(14);
	RDPGPR_CONTEXT(15);
	RDPGPR_CONTEXT(16);
	RDPGPR_CONTEXT(17);
	RDPGPR_CONTEXT(18);
	RDPGPR_CONTEXT(19);
	RDPGPR_CONTEXT(20);
	RDPGPR_CONTEXT(21);
	RDPGPR_CONTEXT(22);
	RDPGPR_CONTEXT(23);
	RDPGPR_CONTEXT(24);
	RDPGPR_CONTEXT(25);
	RDPGPR_CONTEXT(26);
	RDPGPR_CONTEXT(27);
	RDPGPR_CONTEXT(28);
	RDPGPR_CONTEXT(29);
	RDPGPR_CONTEXT(30);
	RDPGPR_CONTEXT(31);

#undef RDPGPR_CONTEXT
}

void k_write_current_pss(const struct ou_context *context)
{
#define WRPGPR_CONTEXT(n)				\
do {							\
	if (context->mask_regs & CTX_MASK_REG_GPR(n)) {	\
		WRPGPR(context->gpr.by_index[n], $##n);	\
	}						\
} while (0)

	__asm__(".set noat");
	WRPGPR_CONTEXT(1);
	__asm__(".set at");
	WRPGPR_CONTEXT(2);
	WRPGPR_CONTEXT(3);
	WRPGPR_CONTEXT(4);
	WRPGPR_CONTEXT(5);
	WRPGPR_CONTEXT(6);
	WRPGPR_CONTEXT(7);
	WRPGPR_CONTEXT(8);
	WRPGPR_CONTEXT(9);
	WRPGPR_CONTEXT(10);
	WRPGPR_CONTEXT(11);
	WRPGPR_CONTEXT(12);
	WRPGPR_CONTEXT(13);
	WRPGPR_CONTEXT(14);
	WRPGPR_CONTEXT(15);
	WRPGPR_CONTEXT(16);
	WRPGPR_CONTEXT(17);
	WRPGPR_CONTEXT(18);
	WRPGPR_CONTEXT(19);
	WRPGPR_CONTEXT(20);
	WRPGPR_CONTEXT(21);
	WRPGPR_CONTEXT(22);
	WRPGPR_CONTEXT(23);
	WRPGPR_CONTEXT(24);
	WRPGPR_CONTEXT(25);
	WRPGPR_CONTEXT(26);
	WRPGPR_CONTEXT(27);
	WRPGPR_CONTEXT(28);
	WRPGPR_CONTEXT(29);
	WRPGPR_CONTEXT(30);
	WRPGPR_CONTEXT(31);

#undef WRPGPR_CONTEXT
}
