macro(add_sources TARGET)
	foreach (_source IN ITEMS ${ARGN})
		if (IS_ABSOLUTE "${_source}")
			set(_source_abs "${_source}")
		else()
			get_filename_component(_source_abs "${_source}" ABSOLUTE)
		endif()
		set_property(GLOBAL APPEND PROPERTY "${TARGET}_SOURCES" "${_source_abs}")
	endforeach()
endmacro()

macro(get_sources VAR TARGET)
	get_property("${VAR}" GLOBAL PROPERTY "${TARGET}_SOURCES")
endmacro()

macro(set_link_script TARGET SCRIPT)
	if (IS_ABSOLUTE "${SCRIPT}")
		set(_script_abs "${SCRIPT}")
	else()
		get_filename_component(_script_abs "${SCRIPT}" ABSOLUTE)
	endif()
	set_property(GLOBAL PROPERTY "${TARGET}_LINK_SCRIPT" "${_script_abs}")
endmacro()

macro(get_link_script VAR TARGET)
	get_property("${VAR}" GLOBAL PROPERTY "${TARGET}_LINK_SCRIPT")
endmacro()

macro(get_link_script_flags VAR TARGET)
	get_link_script(_link_script "${TARGET}")
	if ("${_link_script}" STREQUAL "")
		set("${VAR}" "")
	else()
		set("${VAR}" "-T \"${_link_script}\"")
	endif()
endmacro()

macro(finish_executable TARGET)
	get_sources(_sources "${TARGET}")
	get_link_script_flags(_ldflags "${TARGET}")
	get_link_script(_ldscript "${TARGET}")

	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${_ldflags}")
	add_executable("${TARGET}" ${_sources})
	set_property(TARGET "${TARGET}" APPEND PROPERTY LINK_DEPENDS ${_ldscript})
endmacro()

macro(finish_library TARGET)
	get_sources(_sources "${TARGET}")
	get_link_script_flags(_ldflags "${TARGET}")
	get_link_script(_ldscript "${TARGET}")

	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${_ldflags}")
	add_library("${TARGET}" ${_sources})
	set_property(TARGET "${TARGET}" APPEND PROPERTY LINK_DEPENDS ${_ldscript})
endmacro()
